#!/usr/bin/env bash
# update_ssh_config.sh — write ~/.ssh/config.d/dev-box.generated.conf based on
# Terraform outputs so `ssh dev-box` stays stable even as spot IPs change.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

HOST_ALIAS="${1:-dev-box}"
USER_NAME="${2:-ec2-user}"

IP="$(terraform -chdir="$REPO_DIR" output -raw ssh_host 2>/dev/null || true)"
if [ -z "$IP" ]; then
  IP="$(terraform -chdir="$REPO_DIR" output -raw public_ip 2>/dev/null || true)"
fi
KEY_NAME="$(terraform -chdir="$REPO_DIR" output -raw key_name 2>/dev/null || true)"
INSTANCE_ID="$(terraform -chdir="$REPO_DIR" output -raw instance_id 2>/dev/null || true)"

if [ -z "$IP" ]; then
  echo "No ssh_host/public_ip available. Is the box stopped (enable_instance=false)?" >&2
  exit 1
fi
if [ -z "$KEY_NAME" ]; then
  echo "Missing key_name output. Re-run 'terraform apply' and try again." >&2
  exit 1
fi
if [ -z "$INSTANCE_ID" ]; then
  echo "NOTE: instance_id is empty. The dev box is currently stopped (enable_instance=false). SSH will not connect until started." >&2
fi

SSH_DIR="$HOME/.ssh"
CFG_DIR="$SSH_DIR/config.d"
CFG_FILE="$CFG_DIR/${HOST_ALIAS}.generated.conf"
KEY_FILE="$SSH_DIR/${KEY_NAME}.pem"

mkdir -p "$CFG_DIR"
chmod 700 "$SSH_DIR" "$CFG_DIR" 2>/dev/null || true

if [ ! -f "$KEY_FILE" ]; then
  echo "Key file not found: $KEY_FILE" >&2
  echo "Expected your EC2 keypair PEM to be named like: ~/.ssh/${KEY_NAME}.pem" >&2
  exit 1
fi

cat > "$CFG_FILE" <<EOF
# AUTOGENERATED by iac-dev-box/scripts/update_ssh_config.sh
# Do not edit by hand. Re-run the script after terraform apply.

Host $HOST_ALIAS
  HostName $IP
  Port 22
  User $USER_NAME
  IdentityFile $KEY_FILE
  ForwardAgent yes
  # Disposable box: instances get replaced behind a stable IP, so host keys churn.
  # Avoid "REMOTE HOST IDENTIFICATION HAS CHANGED" blocking workflows.
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
  ServerAliveInterval 60
  ServerAliveCountMax 3
  IdentitiesOnly yes
  AddKeysToAgent yes
  # Keep host keys stable even when IP changes
  HostKeyAlias $HOST_ALIAS
EOF

chmod 600 "$CFG_FILE" 2>/dev/null || true
echo "Wrote $CFG_FILE (HostName=$IP)"
